apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-app-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: app
  namespaceSelector:
    matchNames:
      - application
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
